#!/bin/bash





#SBATCH --time=24:00:00   # walltime
#SBATCH --ntasks=4   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem=4G   # memory per CPU core
#SBATCH -J "ca_T1F_3D"   # job name
#SBATCH --output "ca_T1F_3D"

#Upload Module
module load GCC/11.2.0
module load cutadapt/3.5

# Change me!
SAMPLE= (SAMPLE NAME)

# run cutadapt v3.5
cutadapt -a AGATCGGAAGAGC -A AGATCGGAAGAGC -m 50 -q 15 -j 0 \
-o /scratch/group/kitchen-group/lab/michael/Cx_Gendiversity/Filtered_Reads/${SAMPLE}_filtered_1.fastq \
-p /scratch/group/kitchen-group/lab/michael/Cx_Gendiversity/Filtered_Reads/${SAMPLE}_filtered_2.fastq \
/scratch/group/kitchen-group/lab/michael/Cx_Gendiversity/Raw_Data/${SAMPLE}_1.fastq.gz \
/scratch/group/kitchen-group/lab/michael/Cx_Gendiversity/Raw_Data/${SAMPLE}_2.fastq.gz




